/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  ecma: [{type: 'autogenerated', dirName: '02.js&ts'}],
  java: [{type: 'autogenerated', dirName: '11.java'}],
  go: [{type: 'autogenerated', dirName: '12.go'}],
  linux: [{type: 'autogenerated', dirName: '21.linux'}],
  database: [{type: 'autogenerated', dirName: '13.database'}],
  "算法与数据结构": [{type: 'autogenerated', dirName: '31.algorithms'}],
  economist: [{type: 'autogenerated', dirName: '41.economist'}],
  books: [{type: 'autogenerated', dirName: '42.books'}],
};

module.exports = sidebars;
