/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	ecma: [{
		type: 'autogenerated',
		dirName: '02.js&ts'
	}],
	
	go: [{
		type: 'autogenerated',
		dirName: '11.go'
	}],
	php: [{
		type: 'autogenerated',
		dirName: '12.php'
	}],
	java: [{
		type: 'autogenerated',
		dirName: '13.java'
	}],
	linux: [{
		type: 'autogenerated',
		dirName: '21.linux'
	}],
	mysql: [{
		type: 'autogenerated',
		dirName: '22.mysql'
	}],
	redis: [{
		type: 'autogenerated',
		dirName: '23.redis'
	}],
	english: [{
		type: 'autogenerated',
		dirName: '41.english'
	}],
};

module.exports = sidebars;
